rename the example ignore marker to `#[spruce_example(ignore)]` print with colors when running exmples

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,6 +9,11 @@ on:
 env:
   CARGO_TERM_COLOR: always
   RUSTFLAGS: "-Dwarnings"
+  
+  Green: "\e[0;32m"
+  Yellow: "\e[0;33m"
+  Red: "\033[0;31m"
+  NC: "\e[0m" # No Color
 
 jobs:
   build:
@@ -28,18 +33,22 @@ jobs:
 
       - name: Run examples
         run: |
-          skip_marker="#[spruce_example(run(skip=true))]"
+          ignore_marker='#[spruce_example(ignore)]'
+          echo -e "${Green}Running examples...${NC}"
           for example in examples/*.rs
           do
-            if ! grep -q "$skip_marker" "$example"; then
-              cargo run --example "$(basename "${example%.rs}")" -- $args
+            if grep -Fq "$ignore_marker" "$example"; then
+              echo -e "example $example ... ${Yellow}ignored${NC}"
+            else
+              echo -e "example $example ..."
+              cargo run --example "$(basename "${example%.rs}")" --target x86_64-unknown-linux-gnu -- $args
+              echo -e "${Green}ok${NC}"
             fi
           done
 
       - name: Run scripts tests
         run: |
           test_sync_md_includes() {
-          RED='\033[0;31m'
           local tmp="/tmp/test-md-includes"
           rm -rf "$tmp"
           local marker="test-42-42-42"
@@ -50,14 +59,13 @@ jobs:
             echo '```' >> "$tmp/test.md"
             ./scripts/sync-md-includes.sh "$tmp/test.md"
             if ! grep -q "$marker" "$tmp/test.md"; then
-          echo "${RED}test failed: test_sync_md_includes"
-            exit 1
+              echo -e "${Red}test failed: test_sync_md_includes${NC}"
+              exit 1
             fi
           }
           test_sync_md_includes
           
           test_sync_rustdoc_includes() {
-          RED='\033[0;31m'
           local tmp="/tmp/test-md-includes"
           rm -rf "$tmp"
           local marker="test-42-42-42"
@@ -68,8 +76,8 @@ jobs:
             echo '//! ```' >> "$tmp/test2.rs"
             ./scripts/sync-rustdoc-includes.sh "$tmp"
             if ! grep -q "$marker" "$tmp/test2.rs"; then
-          echo "${RED}test failed: test_sync_rustdoc_includes"
-            exit 1
+              echo -e "${Red}test failed: test_sync_rustdoc_includes${NC}"
+              exit 1
             fi
           }
           test_sync_rustdoc_includes
