fix CI scripts tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -49,48 +49,51 @@ jobs:
       - name: Run scripts tests
         run: |
           test_sync_md_includes() {
-            echo "test sync_md_includes ..."
-            local tmp="/tmp/test-md-includes"
-            rm -rf "$tmp"
-            local marker="test-42-42-42"
-            mkdir "$tmp"
-            echo "$marker" > "$tmp/test.rs"
-            echo "<!-- INCLUDE-RUST: $tmp/test.rs -->" > "$tmp/test.md"
-            echo '```rust' >> "$tmp/test.md"
-            echo '```' >> "$tmp/test.md"
-            sh scripts/sync-md-includes.sh "$tmp/test.md"
-            count=$(awk -v text="$marker" 'BEGIN {count=0} {count += gsub(text, "")} END {print count}' "$tmp/test.md")
-            if [ "$count" -ne 1 ]; then
-              echo -e "${Red}failed: test_sync_md_includes${NC}"
-              exit 1
-            fi
+          echo "test sync_md_includes ..."
+          local tmp="/tmp/test-md-includes"
+          rm -rf "$tmp"
+          local marker="test-42-42-42"
+          mkdir "$tmp"
+          echo "$marker" > "$tmp/test.rs"
+          echo '<!-- INCLUDE-RUST: '"$tmp"'/test.rs -->' > "$tmp/test.md"
+          echo '```rust' >> "$tmp/test.md"
+          echo '```' >> "$tmp/test.md"
+          sh scripts/sync-md-includes.sh "$tmp/test.md"
+          count=$(awk -v text="$marker" 'BEGIN {count=0} {count += gsub(text, "")} END {print count}' "$tmp/test.md")
+          if [ "$count" -ne 1 ]; then
+            echo -e "${Red}failed: test_sync_md_includes${NC}"
+            exit 1
+          fi
             echo "${Green}ok${NC}"
           }
           test_sync_md_includes
           
           test_sync_rustdoc_includes() {
-            echo "test  sync_rustdoc_includes ..."
-            local tmp="/tmp/test-rustdoc-includes"
-            rm -rf "$tmp"
-            local marker="test-42-42-42"
-            mkdir "$tmp"
-            echo "$marker" > "$tmp/test.rs"
-            echo "//! <!-- INCLUDE-RUST: $tmp/test.rs -->" > "$tmp/test2.rs"
-            echo '//! ```' >> "$tmp/test2.rs"
-            echo '//! ```' >> "$tmp/test2.rs"
-            echo "//! <!-- INCLUDE-RUST: $tmp/test.rs -->" >> "$tmp/test2.rs"
-            echo '//! ```ignore' >> "$tmp/test2.rs"
-            echo '//! ```' >> "$tmp/test2.rs"
-            echo "  // <!-- INCLUDE-RUST: $tmp/test.rs -->" >> "$tmp/test2.rs"
-            echo '  // ```' >> "$tmp/test2.rs"
-            echo '  // ```' >> "$tmp/test2.rs"
-            sh scripts/sync-rustdoc-includes.sh "$tmp"
-            count=$(awk -v text="$marker" 'BEGIN {count=0} {count += gsub(text, "")} END {print count}' "$tmp/test2.rs")
-            if [ "$count" -ne 3 ]; then
-              echo -e "${Red}failed: test_sync_rustdoc_includes${NC}"
-              exit 1
-            fi
-            echo "${Green}ok${NC}"
+          echo "test  sync_rustdoc_includes ..."
+          local tmp="/tmp/test-rustdoc-includes"
+          rm -rf "$tmp"
+          local marker="test-42-42-42"
+          mkdir "$tmp"
+          echo "$marker" > "$tmp/test.rs"
+          echo '//! <!-- INCLUDE-RUST: '"$tmp"'/test.rs -->' > "$tmp/test2.rs"
+          echo '//! ```' >> "$tmp/test2.rs"
+          echo '//! ```' >> "$tmp/test2.rs"
+          echo '//! <!-- INCLUDE-RUST: '"$tmp"'/test.rs -->' >> "$tmp/test2.rs"
+          echo '//! ```ignore' >> "$tmp/test2.rs"
+          echo '//! ```' >> "$tmp/test2.rs"
+          echo '  // <!-- INCLUDE-RUST: '"$tmp"'/test.rs -->' >> "$tmp/test2.rs"
+          echo '  // ```' >> "$tmp/test2.rs"
+          echo '  // ```' >> "$tmp/test2.rs"
+          echo '  // <!-- INCLUDE-RUST: '"$tmp"'/test.rs -->' >> "$tmp/test2.rs"
+          echo '  // ```ignore' >> "$tmp/test2.rs"
+          echo '  // ```' >> "$tmp/test2.rs"
+          sh scripts/sync-rustdoc-includes.sh "$tmp"
+          count=$(awk -v text="$marker" 'BEGIN {count=0} {count += gsub(text, "")} END {print count}' "$tmp/test2.rs")
+          if [ "$count" -ne 4 ]; then
+            echo -e "${Red}failed: test_sync_rustdoc_includes${NC}"
+            exit 1
+          fi
+          echo "${Green}ok${NC}"
           }
           test_sync_rustdoc_includes
 
